site_name: MACH2/MACH2-Viz Documentation
theme: material
theme: 
  name: material
  logo: assets/favicon.ico
  features:
    - content.tooltips
    - content.code.copy
nav:
  - Quick Start:
    - Basic Features: feature.md
    - Installation: installation.md
    - Quick Start Guide: quickstart.md
  - Tutorial:
    - MACH2/MACH2-Viz Documentation: tutorial.md
    - Example Usage: examples.md
  - Contributing:
    - Contributing: contributions.md
    - Uploading Datasets: upload.md
    - Creating Documentation: doc.md
extra_css:
  - css/custom.css
markdown_extensions:
  - attr_list