site_name: MACH2/MACH2-Viz Documentation
theme: 
  name: material
  logo: assets/favicon.ico
  features:
    - content.tooltips
    - content.code.copy
    - content.code.annotate
nav:
  - Quick Start:
    - Basic Features: feature.md
    - Installation: installation.md
    - Quick Start Guide: quickstart.md
  - Tutorial:
    - MACH2/MACH2-Viz Documentation: tutorial.md
    - Example Usage: examples.md
  - Contributing:
    - Contributing: contributions.md
    - Uploading Datasets: upload.md
    - Creating Documentation: doc.md
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/elkebir-group/MACH2/tree/main
    - icon: fontawesome/solid/globe
      link: https://elkebir-group.github.io/mach2-viz/
extra_css:
  - css/custom.css
markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences